{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cloud-native-kubernetes-ingress
  namespace: {{ .Values.namespace }}
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: {{ .Values.ingress.className }}
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          {{- range .Values.services }}
          - path: /api/{{ .apiPath }}(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: {{ .name }}
                port:
                  number: {{ .port }}
          {{- end }}
{{- end }}
